### ISSUE TITLE
New Page: Events

### ISSUE THREAD

**Issue by ASafaeirad** [fullstacksjs/fullstacksjs#6]
The objective of this issue is to create a new page called "Events Page" on our community's website. This page will showcase all the past and upcoming events of the community.

The "Events Page" should include the following features:

1. Display of Past and Upcoming Events:
   The page should display a list of past events and upcoming events. The events should be displayed in reverse chronological order with the most recent event at the top. Each event should have a thumbnail, title, date, and time.

2. Subscription Button and Subscribers Count:
   Each event should have a subscription button that users can use to subscribe to the event. The button should display the number of subscribers for the event. When a user subscribes to an event, the number of subscribers should increase, and the button should change to "unsubscribe". If a user unsubscribes, the number of subscribers should decrease, and the button should change back to "subscribe".

3. Lecturers List:
   Each event should have a list of lecturers who will be speaking at the event. The list should include their avatar and a hover popup to display their name.

4. CMS Integration:
   The website should be built with a Content Management System (CMS) that will allow for easy creation and management of the events and thumbnails.

5. BaaS Integration:
   A Backend as a Service (BaaS) solution should be integrated to store the subscriber information for each event.

6. Auth:
   An authentication module should be implemented to allow users to log in to the system. Only a GitHub OAuth login should be accepted.

### Tasks:

- [x] Design the "Events Page" layout and UI. [Figma](https://www.figma.com/file/SU9CedDAAacGIwpUjapvAI/Landing-Page?type=design&node-id=214-5571&t=ZmPgVDfh3U54szbI-0).
- [] Development of the "Events Page" UI.
- [] Integration of a CMS solution to manage the content on the page.
- [] Implementation of an authentication module with GitHub OAuth login.
- [] Integration of the subscription button and subscribers count feature.
- [] Testing and debugging of the implemented features.
- [] Deployment of the "Events Page" to the community website landing page.
